name: markup_text
description: Flutter widget to use Markup to easily create formatted Text with colors, style and links.
version: 0.2.0
homepage: https://github.com/poqueque/markup_text

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^5.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: