name: markup_text_plus
description: Flutter widget to use Markup to easily create formatted Text with colors, style and links.
version: 0.2.0
homepage: https://github.com/4akloon/markup_text_plus


environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter: